### ISSUE TITLE
Ser ikke ut som att lenker med highway=pedestrian kommer med ut i datasetet?

### ISSUE THREAD

**Issue by OpenTNF** [jetgeo/Sykkeldata#6]
Denne lenken http://www.openstreetmap.org/way/135175582 har ikke blivit med ut i sista datasetet (20150921). 
La du med lenker med highway=pedestrian ?

**Comment by petlof** [comment]
Sjävlklart var det jag och ingen annan som la issuen :-)

**Comment by jetgeo** [comment]
Hm. Ser ut til at highway=pedestrian har falt ut igjen. Måtte sjonglere litt mellom FME-versjoner, mulig en gammel versjon av produksjonsløypa lurte seg inn. Tror det er retta nå, kjører ny tilrettelegging.
