### ISSUE TITLE
Ulogisk omveg på Ridabu

### ISSUE THREAD

**Issue by jetgeo** [jetgeo/Sykkeldata#7]
Har ingen forklaring på denne, nettverket ser korrekt ut:
http://sykkelveg.no/latest?routeRequestJSON=%7b"routeType"%3A0,"effort"%3A0,"locations"%3A%5B%7b"easting"%3A289619.92382813,"northing"%3A6746847.1547852,"elevation"%3A0%7d,%7b"easting"%3A290103.87304688,"northing"%3A6747093.0961914,"elevation"%3A0%7d%5D,"barriers"%3A"GEOMETRYCOLLECTION()","language"%3A"no","epsg"%3A"EPSG%3A32633","includeGML"%3Afalse,"includeWKT"%3Atrue%7d&zoom=15&lat=60.80245&lon=11.13715&layers=B00TTFFTTTT
![2015-10-31_1557](https://cloud.githubusercontent.com/assets/7501876/10864244/2ef02224-7fe8-11e5-8722-64682aaa3c81.png)

**Comment by petlof** [comment]
Tror förklaringen i krysset på sykkelveien här:

Høydeprofilen ger att man åker 5 meter uppåt i höjd på ca. 3 meter vei, (> 45% lutning). I energimodellen är det omuligt att ta sig fram i den lutningen, så den kommer falla tillbaka på "gång" i 1km/h. Vilket gör att man "tjänar" energi på detta hvis man får igen det på slutet av ruten. 
Lite som en Warphole :-)

![image](https://cloud.githubusercontent.com/assets/1931986/10876711/7d39f312-813f-11e5-831d-101a053c6f6d.png)

**Comment by jetgeo** [comment]
Høydegapet oppstår når OpenStreetMap-lenkene draperes på en terrengmodell basert på NVDB-lenkene. Her er det en undergang, og den aktuelle lenken har da fått høyde fra vegen over undergangen. 
Produksjonsløypa er nå justert slik at drapering skjer til nærmeste punkt, og uten innføring av ekstra punkt på linjene. Så lenge det ikke er knekkpunkter inne på linja blir det noe bedre. Sørenden på linja får høyde fra gang- og sykkelvegen sør for undergangen, mens nordenden får høyde fra vegen opp mot kirka. Stigningen på 5 m blir nå fordelt over en lengde på ca 24m. I virkeligheten starter stigningen omtrent ved nordenden av denne lenka. Dette viser at vi har en utfordring med OSM-data. Denne lenken kunne også godt ha vært inne i NVDB som kommunal gang- og sykkelveg.

**Comment by petlof** [comment]
Vi lägger även in en fix i motorn att man ikke gör som nu, hvis man finner för branta stigningar så loggar vi det och lägger på 10s reisetid per høydemeter ovanpå beräknad kostnad.

**Comment by petlof** [comment]
Har lagt ut ny version av rutemotor som löser problemet också
