### ISSUE TITLE
Felaktig snappning mellan nivåer vid fredrikstadsbrua

### ISSUE THREAD

**Issue by petlof** [jetgeo/Sykkeldata#9]
Gangveg under fredrikstadsbrua verkar felaktigt snappa in mot huvudveien.

![image](https://cloud.githubusercontent.com/assets/1931986/11559716/56eac4f4-99bb-11e5-9c3f-0bb0caea4ea6.png)

**Comment by jetgeo** [comment]
Vet ikke hvorfor dette har skjedd, men det blir i alle fall riktig nå. Nytt datasett produsert.
